"""security intelligence

Revision ID: 6c222f458559
Revises: b876b720fe30
Create Date: 2026-08-26 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c222f458559'
down_revision: Union[str, None] = 'b876b720fe30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_intelligence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('risk_score', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('indicators', sa.String(), nullable=True),
    sa.Column('related_events', sa.String(), nullable=True),
    sa.Column('related_alerts', sa.String(), nullable=True),
    sa.Column('recommended_actions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_intelligence_created_at'), 'security_intelligence', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_intelligence_source_id'), 'security_intelligence', ['source_id'], unique=False)
    op.create_index(op.f('ix_security_intelligence_source_type'), 'security_intelligence', ['source_type'], unique=False)
    op.create_index(op.f('ix_security_intelligence_user_id'), 'security_intelligence', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_intelligence_user_id'), table_name='security_intelligence')
    op.drop_index(op.f('ix_security_intelligence_source_type'), table_name='security_intelligence')
    op.drop_index(op.f('ix_security_intelligence_source_id'), table_name='security_intelligence')
    op.drop_index(op.f('ix_security_intelligence_created_at'), table_name='security_intelligence')
    op.drop_table('security_intelligence')
    # ### end Alembic commands ###
